version: "2.3"
services:
  be:
    image: "skillbillsrl/developer-arena-be:${TAG}"
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - CONFIT_REPO_ID=${CONFIT_REPO_ID}
      - CONFIT_REPO_SECRET=${CONFIT_REPO_SECRET}
    volumes:
      - preview:/be/preview
  db:
    image: "postgres:10-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=developer-arena
    volumes:
      - lbpgdata:/var/lib/postgresql/data
  fe:
    image: "skillbillsrl/developer-arena-fe:${TAG}"
    depends_on:
      - be
    ports:
      - 8080:8080
    environment:
      - CONFIT_REPO_ID=${CONFIT_REPO_ID}
    volumes:
      - type: bind
        source: ./pages
        target: /app/static/pages
  bo:
    image: "skillbillsrl/developer-arena-bo:${TAG}"
    depends_on:
      - be
    ports:
      - 8081:8081
    environment:
      - CONFIT_REPO_ID=${CONFIT_REPO_ID}

volumes:
    lbpgdata:
        external: true
    preview: