version: "2.3"
services:
  be:
    image: "skillbillsrl/sda-contest-be:${TAG}"
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./config/be.json
        target: /be/config.json
      - preview:/be/preview
  db:
    image: "skillbillsrl/sda-contest-db:${TAG}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  fe:
    image: "skillbillsrl/sda-contest-fe:${TAG}"
    depends_on:
      - be
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./config/fe.json
        target: /app/static/configuration.json
      - type: bind
        source: ./pages
        target: /app/static/pages
  bo:
    image: "skillbillsrl/sda-contest-bo:${TAG}"
    depends_on:
      - be
    ports:
      - 8081:8081
    volumes:
      - type: bind
        source: ./config/bo.json
        target: /app/static/configuration.json

volumes:
    pgdata:
        external: true
    preview:

#cd be && docker build . -t skillbillsrl/sda-contest-be:local && cd .. && cd db && docker build . -t skillbillsrl/sda-contest-db:local && cd .. && cd fe && docker build . -t skillbillsrl/sda-contest-fe:local && cd .. && cd bo && docker build . -t skillbillsrl/sda-contest-bo:local && cd .. && TAG=local docker-compose up
