version: "2.3"
services:
  be:
    image: "skillbillsrl/developer-arena-be:${TAG}"
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - CONFIT_REPOID=${CONFIT_REPOID}
      - CONFIT_TOKEN=${CONFIT_TOKEN_BE}
    volumes:
      - preview:/be/preview
  db:
    image: "skillbillsrl/developer-arena-db:${TAG}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  fe:
    image: "skillbillsrl/developer-arena-fe:${TAG}"
    depends_on:
      - be
    ports:
      - 8080:8080
    environment:
      - CONFIT_REPOID=${CONFIT_REPOID}
    volumes:
      - type: bind
        source: ./pages
        target: /app/static/pages
  bo:
    image: "skillbillsrl/developer-arena-bo:${TAG}"
    depends_on:
      - be
    ports:
      - 8081:8081
    environment:
      - CONFIT_REPOID=${CONFIT_REPOID}

volumes:
    pgdata:
        external: true
    preview:

#cd be && docker build . -t skillbillsrl/developer-arena-be:local && cd .. && cd db && docker build . -t skillbillsrl/developer-arena-db:local && cd .. && cd fe && docker build . -t skillbillsrl/developer-arena-fe:local && cd .. && cd bo && docker build . -t skillbillsrl/developer-arena-bo:local && cd .. && TAG=local docker-compose up
