TAG=${TAG:-latest}

DOCKER_IMG_FE=${DOCKER_IMG_FE:-sda-contest-fe}
FE_PORT=${FE_PORT:-8080}
FE_HOST=${FE_HOST:-localhost}
FE_ADDR=$FE_HOST:$FE_PORT

DOCKER_IMG_BE=${DOCKER_IMG_BE:-sda-contest-be}
BE_PORT=${BE_PORT:-3000}
BE_HOST=${BE_HOST:-localhost}
BE_ADDR=$BE_HOST:$BE_PORT

DOCKER_IMG_DB=${DOCKER_IMG_DB:-sda-contest-db}
DB_PORT=${DB_PORT:-5432}
DB_HOST=${DB_HOST:-localhost}
DB_ADDR=$DB_HOST:$DB_PORT
DB_USER=${DB_USER:-postgres}
DB_PASSWD=${DB_PASSWD:-1234}
